repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.1
    hooks:
      # Run the linter.
      - id: ruff-check
        files: ^apps/
      # Run the formatter.
      - id: ruff-format
        files: ^apps/

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.6'
    hooks:
      - id: djhtml
        files: ^apps/.*\.html$
        args: ['--tabwidth', '4']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        files: ^apps/.*\.(js|css|scss)$
        args:
          - '--tab-width=2'
          - '--single-quote'
          - '--trailing-comma=es5'